import type { Metadata } from 'next';
import Footer from './Footer';
import './globals.css';
import Header from './Header';

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: ' Next 14 Blog',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="container mx-auto bg-slate-700 text-slate-50">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
